name: Dev Backend

on:
  push:
    branches:
        - dev

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use node js
        uses: actions/setup-node@v1
        with:
         node-version: ${{ matrix.node-version }}
      - name: npm install and build
        run: |
          npm install
          npm run build

        env: 
          CI: true   


  depoly:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
     - name: SSH deploy
       uses: appleboy/ssh-action@master
       with:
          host: ${{ secrets.HOSTDEV }}
          username:  ${{ secrets.USERDEV }}
          key:  ${{ secrets.KEYDEV }}
          port:  ${{ secrets.PORTDEV }}
          script: |
              curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.39.3/install.sh    | bash
              . ~/.nvm/nvm.sh

               nvm instal 18
               npm install -g pm2
               cd /home/ubuntu/deploy/
               mkdir backend
               cd backend
               git pull origin dev
               npm install
               npm run build
               pm2 restart api
