name: master Backend

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use node js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and build
        run: |
          npm install
          npm run build

        env:
          CI: true

  deploy:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: SSH deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOSTMASTER }}
          username: ${{ secrets.USERMASTER }}
          key: ${{ secrets.KEYMASTER }}
          port: ${{ secrets.PORTMASTER }}
          script: |
            curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.39.3/install.sh    | bash
            . ~/.nvm/nvm.sh

             nvm instal 18
             npm install -g pm2
             cd /home/ubuntu/
             mkdir deploy
             cd deploy
             mkdir backend
             cd backend
             git pull origin master
             npm install
             npm run build
             pm2 restart api
